apiVersion: apps/v1
kind: Deployment
metadata:
  name: truyumcloud-deployment
  labels:
    app: truyumcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: truyumcloud  
  template:
    metadata:
      labels:
        app: truyumcloud
    spec:
      containers:
      - name: dnazurecontregistry
        image: dnazurecontregistry.azurecr.io/conrepo:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: secret
---
apiVersion: v1
kind: Service
metadata:
  name: truyumcloudsvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: truyumcloud