apiVersion: apps/v1
kind: Deployment
metadata:
  name: truyum_azurecloud-deployment
  labels:
    app: TruYum_AzureCloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: TruYum_AzureCloud  
  template:
    metadata:
      labels:
        app: TruYum_AzureCloud
    spec:
      containers:
      - name: dnazurecontregistry
        image: dnazurecontregistry.azurecr.io/conrepo:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: secret
---
apiVersion: v1
kind: Service
metadata:
  name: truyum_azurecloudsvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: TruYum_AzureCloud